name: 🐛 Bug report
description: Something isn't working as expected
title: "bug: <short summary>"
labels: ["bug", "needs-triage"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug and expected vs. actual behavior.
      placeholder: "It should..., but instead it..."
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: List exact steps to reproduce.
      placeholder: "1) ...  2) ...  3) ..."
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version / commit SHA
      placeholder: "e.g., v0.3.2 or 744b37a"
  - type: textarea
    id: logs
    attributes:
      label: Logs / stack traces
      render: shell
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - CI/CD
        - PCS Engine
        - Data Adapters (IBKR / Options)
        - Web UI / Reports
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-checks
      options:
        - label: I searched existing issues.
          required: true
        - label: I can reproduce on the latest main.
